[versions]
accompanist = "0.34.0"
activity-compose = "1.8.2"
agp = "8.2.2"
app-compat = "1.6.1"
compose-bom = "2024.01.00"
compose-compiler-report-generator = "1.1.0"
compose-lint-checks = "1.3.1"
compose-material3 = "1.2.0-rc01"
core-ktx = "1.12.0"
coroutines = "1.7.3"
dagger-hilt = "2.50"
dagger-hilt-extensions = "1.1.0"
detekt = "1.23.5"
kotlin = "1.9.22"
kotlinter = "4.2.0"
ksp = "1.9.22-1.0.17"
leakcanary = "2.13"
lifecycle = "2.7.0"
material = "1.12.0-alpha03"
navigation_compose = "2.7.6"
orbit = "6.1.0"
room = "2.6.1"
spotless = "6.25.0"
timber = "5.0.1"
versions = "0.51.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "dagger-hilt-extensions" }
dagger-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-extensions" }
dagger-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "dagger-hilt-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_compose" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-vm = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
implementation = [
    "accompanist-permissions",
    "activity-compose",
    "app-compat",
    "compose-animation",
    "compose-material3",
    "compose-material3-windowsizeclass",
    "compose-ui",
    "compose-ui-tooling",
    "core-ktx",
    "coroutines-android",
    "dagger-hilt-android",
    "dagger-hilt-navigation-compose",
    "kotlin-stdlib",
    "lifecycle-runtime-ktx",
    "material",
    "material-icons-extended",
    "navigation_compose",
    "orbit-compose",
    "orbit-vm",
    "room-ktx",
    "room-runtime",
    "timber"
]
ksp = [
    "dagger-hilt-android-compiler",
    "dagger-hilt-compiler",
    "room-compiler"
]
lint-checks = [
    "compose-lint-checks"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler-report-generator = { id = "dev.shreyaspatil.compose-compiler-report-generator", version.ref = "compose-compiler-report-generator" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
