name: Ktlint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup JDK 17
        id: setup-java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run ktlint
        run: ./gradlew lintKotlin
